CREATE TABLE `devrebel-big-query-database.dev_hotel_costar.CompsetData`
(
  index INT64,
  property_code STRING,
  census_id INT64,
  cs_no STRING,
  cs_reference STRING,
  chain_id STRING,
  property_name STRING,
  brand STRING,
  city STRING,
  state STRING,
  country STRING,
  available_rms INT64,
  open_date INT64,
  cs_type STRING,
  cs_owner STRING,
  compliance_status STRING,
  delete_on_date INT64,
  cs_status STRING,
  cs_census_id INT64,
  cs_property_name STRING,
  cs_brand STRING,
  cs_city STRING,
  cs_state STRING,
  cs_country STRING,
  cs_rms INT64,
  cs_open_date INT64,
  creation_date INT64,
  legacy_position INT64,
  cs_available_rms INT64
);