CREATE TABLE `devrebel-big-query-database.dev_hotel_costar.metrics_fact_costar`
(
  index INT64 OPTIONS(description="A sequential identifier for records."),
  property_code STRING OPTIONS(description="A unique identifier for a specific property."),
  str_id INT64 OPTIONS(description="An identifier associated with a property's census data."),
  cs_no STRING OPTIONS(description="A unique identifier for a competitive set."),
  cs_reference STRING OPTIONS(description="A reference identifier for a competitive set."),
  cs_id STRING OPTIONS(description="An identifier for the hotel chain to which a property belongs."),
  property_name STRING OPTIONS(description="The name of the property."),
  property_shortname STRING OPTIONS(description="The short name of the  property."),
  brand STRING OPTIONS(description="The brand name of the property."),
  city STRING OPTIONS(description="The city where the property is located."),
  state STRING OPTIONS(description="The state where the property is located."),
  country STRING OPTIONS(description="The country where the property is located."),
  available_rms INT64 OPTIONS(description="The number of available rooms at the property."),
  open_date DATE OPTIONS(description="The date when the property opened."),
  cs_type STRING OPTIONS(description="The type of competitive set."),
  cs_owner STRING OPTIONS(description="The owner of the competitive set."),
  compliance_status STRING OPTIONS(description="The compliance status of the competitive set."),
  delete_on_date DATE OPTIONS(description="The date on which a record is marked for deletion."),
  cs_status STRING OPTIONS(description="The current status of the competitive set."),
  cs_str_id INT64 OPTIONS(description="An identifier associated with a competitive set's census data."),
  cs_property_name STRING OPTIONS(description="The name of a property within the competitive set."),
  cs_brand STRING OPTIONS(description="The brand name of a property within the competitive set."),
  cs_city STRING OPTIONS(description="The city where a competitive set property is located."),
  cs_state STRING OPTIONS(description="The state where a competitive set property is located."),
  cs_country STRING OPTIONS(description="The country where a competitive set property is located."),
  cs_available_rms INT64 OPTIONS(description="The number of available rooms for a property within the competitive set."),
  cs_open_date DATE OPTIONS(description="The opening date for a property within the competitive set."),
  creation_date DATE OPTIONS(description="The date when the record was created."),
  legacy_position INT64 OPTIONS(description="A historical or inherited position value.")
);