CREATE TABLE `devrebel-big-query-database.Pace.Pace_RoomType`
(
  property_code STRING OPTIONS(description="Property code"),
  property_name STRING OPTIONS(description="Property name"),
  physical_capacity INT64 OPTIONS(description="The total number of rooms available for sale represents the property's fixed maximum inventory. This count excludes any rooms that are out of order."),
  property_shortname STRING OPTIONS(description="Property names abbreviated within charts and graphs when space constraints prevent the display of longer names."),
  rms_roomtype STRING OPTIONS(description="Filters data for consumed revenue, room nights, and other essential metrics by grouping individual room types under the room type."),
  rms_roomtype_class STRING OPTIONS(description="Filters data for consumed revenue, room nights, and other essential metrics by grouping individual room types under the room type class. The room class groups individual room types together based on features, size, view, or amenities."),
  dow STRING OPTIONS(description="Day of week"),
  stay_date DATE OPTIONS(description="Filters the information and consumed revenue and other metrics based on the guest's stay dates."),
  stay_date_py DATE OPTIONS(description="Filters the information and consumed revenue and other metrics based on the guest's stay dates."),
  rms INT64 OPTIONS(description="Competitor number of rooms"),
  rms_py INT64 OPTIONS(description="Competitor number of rooms"),
  rms_stly INT64 OPTIONS(description="Rooms on the books same time prior year"),
  rms_st2y INT64 OPTIONS(description="Total group room nights on the books as of two years ago"),
  rms_st19 INT64 OPTIONS(description="Rooms on the books same time 2019"),
  adr FLOAT64 OPTIONS(description="Average Dollar Rate (ADR) represents the average income generated per room sold during a given timeframe. It is determined by dividing the total room revenue by the number of rooms sold."),
  adr_py FLOAT64 OPTIONS(description="Average Dollar Rate (ADR) represents the average income generated per room sold during a given timeframe. It is determined by dividing the total room revenue by the number of rooms sold."),
  adr_fct_py FLOAT64 OPTIONS(description="System-generated ADR forecast refers to the projected average daily rate (ADR) calculated by hotel revenue management or forecasting systems. These predictions are based on factors such as historical data, booking patterns, market trends, and pricing strategies. They assist hotels in forecasting future revenue performance and making informed pricing decisions."),
  adr_fct FLOAT64 OPTIONS(description="System-generated ADR forecast refers to the projected average daily rate (ADR) calculated by hotel revenue management or forecasting systems. These predictions are based on factors such as historical data, booking patterns, market trends, and pricing strategies. They assist hotels in forecasting future revenue performance and making informed pricing decisions."),
  rev FLOAT64 OPTIONS(description="Total room revenue"),
  rev_py FLOAT64 OPTIONS(description="Total room revenue"),
  rev_stly FLOAT64 OPTIONS(description="Total room revenue on the books as of the same time prior year"),
  rev_st2y FLOAT64 OPTIONS(description="Total room revenue on the books as of two years ago"),
  rev_st19 FLOAT64 OPTIONS(description="Total room revenue on the books as of the same time in 2019"),
  rev_fct FLOAT64 OPTIONS(description="System-Generated Rooms Revenue Forecast refers to the projected rooms revnue calculated by hotel revenue management or forecasting systems. These predictions are based on factors such as historical data, booking patterns, market trends, and pricing strategies. They assist hotels in forecasting future revenue performance and making informed pricing decisions."),
  rev_fct_py FLOAT64 OPTIONS(description="System-Generated Rooms Revenue Forecast refers to the projected rooms revnue calculated by hotel revenue management or forecasting systems. These predictions are based on factors such as historical data, booking patterns, market trends, and pricing strategies. They assist hotels in forecasting future revenue performance and making informed pricing decisions."),
  revpar FLOAT64 OPTIONS(description="Competitive set revenue per available room"),
  revpar_py FLOAT64 OPTIONS(description="Competitive set revenue per available room"),
  revpar_fct FLOAT64 OPTIONS(description="System-Generated RevPAR Forecast refers to the projected RevPAR calculated by hotel revenue management or forecasting systems. These predictions are based on factors such as historical data, booking patterns, market trends, and pricing strategies. They assist hotels in forecasting future revenue performance and making informed pricing decisions."),
  revpar_fct_py FLOAT64 OPTIONS(description="System-Generated RevPAR Forecast refers to the projected RevPAR calculated by hotel revenue management or forecasting systems. These predictions are based on factors such as historical data, booking patterns, market trends, and pricing strategies. They assist hotels in forecasting future revenue performance and making informed pricing decisions."),
  rms_other FLOAT64 OPTIONS(description="Room revenue other current year"),
  rms_other_py FLOAT64 OPTIONS(description="Room revenue other current year"),
  arrivals INT64 OPTIONS(description="The total number of arrivals and the guests or bookings scheduled to check in within the defined period."),
  arrivals_py INT64 OPTIONS(description="The total number of arrivals and the guests or bookings scheduled to check in within the defined period."),
  departures INT64 OPTIONS(description="The total number of departures and the guests or bookings scheduled to check out within the defined period."),
  departures_py INT64 OPTIONS(description="The total number of departures and the guests or bookings scheduled to check out within the defined period."),
  rms_ooo INT64 OPTIONS(description="Out of order rooms current year"),
  rms_ooo_py INT64 OPTIONS(description="Out of order rooms current year"),
  cx INT64 OPTIONS(description="The total number of reservations canceled during a given time frame. This includes all cancellations, regardless of when the bookings were initially made or the intended stay dates."),
  cx_py INT64 OPTIONS(description="The total number of reservations canceled during a given time frame. This includes all cancellations, regardless of when the bookings were initially made or the intended stay dates."),
  no_show INT64 OPTIONS(description="Total No-Shows and refers to guests with confirmed reservations who neither arrived nor canceled their booking restuling in lost occupancy and missed revenue opportunities."),
  no_show_py INT64 OPTIONS(description="Total No-Shows and refers to guests with confirmed reservations who neither arrived nor canceled their booking restuling in lost occupancy and missed revenue opportunities."),
  capacity INT64 OPTIONS(description="Capacity is maximum number of rooms or guests the hotel can accommodate at a given time."),
  capacity_py INT64 OPTIONS(description="Capacity is maximum number of rooms or guests the hotel can accommodate at a given time."),
  remaining_capacity INT64 OPTIONS(description="Remaining capacity is the number of unsold rooms still available for a specific date or time period. It is determined by subtracting the number of rooms already sold or reserved from the total number of available rooms."),
  remaining_capacity_py INT64 OPTIONS(description="Remaining capacity is the number of unsold rooms still available for a specific date or time period. It is determined by subtracting the number of rooms already sold or reserved from the total number of available rooms."),
  overbooking INT64 OPTIONS(description="Overbooking current year"),
  overbooking_py INT64 OPTIONS(description="Overbooking current year"),
  bar STRING OPTIONS(description="The property's current best flexible rate (BAR)—the standard, publicly available rate with the most flexible booking conditions"),
  bar_py STRING OPTIONS(description="The property's current best flexible rate (BAR)—the standard, publicly available rate with the most flexible booking conditions"),
  roomtype STRING OPTIONS(description="Filters data for consumed revenue, room nights, and other essential metrics by grouping individual room types under the room type."),
  roomtype_code STRING OPTIONS(description="The room class groups individual room types together based on features, size, view, or amenities."),
  roomtype_class STRING OPTIONS(description="Filters data for consumed revenue, room nights, and other essential metrics by grouping individual room types under the room type class. The room class groups individual room types together based on features, size, view, or amenities."),
  roomtype_category_code STRING OPTIONS(description="Filters data for consumed revenue, room nights, and other essential metrics by grouping individual room types under the room type class. The room class groups individual room types together based on features, size, view, or amenities."),
  roomtype_category_base STRING OPTIONS(description="Filters data for consumed revenue, room nights, and other essential metrics by grouping individual room types under the room type category. This categorization organizes rooms based on standards, upgrades, suites, and bed types."),
  roomtype_category STRING OPTIONS(description="Filters data for consumed revenue, room nights, and other essential metrics by grouping individual room types under the room type class. The room class groups individual room types together based on features, size, view, or amenities."),
  roomtype_physical_capacity STRING OPTIONS(description="The total number of rooms available for sale within a specific room type reflects the property's fixed maximum inventory. This figure does not include any rooms currently marked as out of order."),
  roomtype_sort STRING OPTIONS(description="Used to control the sorting of dimensions within room types"),
  snapshot_date DATE OPTIONS(description="Filters the date in which the data was collected."),
  ingested_timestamp TIMESTAMP OPTIONS(description="Datetime of data ingestion"),
  sent_to_big_query BOOL OPTIONS(description="Sent to big query"),
  date_sent_to_big_query TIMESTAMP OPTIONS(description="Date when the data was sent to biq query")
)
PARTITION BY stay_date
CLUSTER BY property_code, snapshot_date
OPTIONS(
  partition_expiration_days=60.0
);