CREATE TABLE `devrebel-big-query-database.Pace.Pace_Segment`
(
  property_code STRING OPTIONS(description="Property code"),
  property_name STRING OPTIONS(description="Property name"),
  physical_capacity INT64 OPTIONS(description="The total number of rooms available for sale represents the property's fixed maximum inventory. This count excludes any rooms that are out of order."),
  property_shortname STRING OPTIONS(description="Property names abbreviated within charts and graphs when space constraints prevent the display of longer names."),
  segment STRING OPTIONS(description="Filters values for consumed revenue, room nights, and other metrics based on the Market Segment. These segments are categorized by shared characteristics such as the type of rate, room type, and the booking channel used by the guest."),
  dow STRING OPTIONS(description="Day of week"),
  stay_date DATE OPTIONS(description="Filters the information and consumed revenue and other metrics based on the guest's stay dates."),
  stay_date_py DATE OPTIONS(description="Filters the information and consumed revenue and other metrics based on the guest's stay dates."),
  rms_fct_py INT64 OPTIONS(description="Total number of forecasted room nights"),
  rms_fct INT64 OPTIONS(description="Total number of forecasted room nights"),
  adr_fct_py FLOAT64 OPTIONS(description="System-generated ADR forecast refers to the projected average daily rate (ADR) calculated by hotel revenue management or forecasting systems. These predictions are based on factors such as historical data, booking patterns, market trends, and pricing strategies. They assist hotels in forecasting future revenue performance and making informed pricing decisions."),
  adr_fct FLOAT64 OPTIONS(description="System-generated ADR forecast refers to the projected average daily rate (ADR) calculated by hotel revenue management or forecasting systems. These predictions are based on factors such as historical data, booking patterns, market trends, and pricing strategies. They assist hotels in forecasting future revenue performance and making informed pricing decisions."),
  rev_fct FLOAT64 OPTIONS(description="System-Generated Rooms Revenue Forecast refers to the projected rooms revnue calculated by hotel revenue management or forecasting systems. These predictions are based on factors such as historical data, booking patterns, market trends, and pricing strategies. They assist hotels in forecasting future revenue performance and making informed pricing decisions."),
  rev_fct_py FLOAT64 OPTIONS(description="System-Generated Rooms Revenue Forecast refers to the projected rooms revnue calculated by hotel revenue management or forecasting systems. These predictions are based on factors such as historical data, booking patterns, market trends, and pricing strategies. They assist hotels in forecasting future revenue performance and making informed pricing decisions."),
  rms INT64 OPTIONS(description="Competitor number of rooms"),
  rms_py INT64 OPTIONS(description="Competitor number of rooms"),
  rms_stly INT64 OPTIONS(description="Rooms on the books same time prior year"),
  rms_st2y INT64 OPTIONS(description="Total group room nights on the books as of two years ago"),
  rms_st19 INT64 OPTIONS(description="Rooms on the books same time 2019"),
  adr_py FLOAT64 OPTIONS(description="Average Dollar Rate (ADR) represents the average income generated per room sold during a given timeframe. It is determined by dividing the total room revenue by the number of rooms sold."),
  adr FLOAT64 OPTIONS(description="Average Dollar Rate (ADR) represents the average income generated per room sold during a given timeframe. It is determined by dividing the total room revenue by the number of rooms sold."),
  rev FLOAT64 OPTIONS(description="Total room revenue"),
  rev_py FLOAT64 OPTIONS(description="Total room revenue"),
  rev_stly FLOAT64 OPTIONS(description="Total room revenue on the books as of the same time prior year"),
  projected_rev FLOAT64 OPTIONS(description="Projected revenue based on the hotel’s uploaded forecast, assessed separately from the system's projected revenue."),
  projected_rev_py FLOAT64 OPTIONS(description="Projected revenue based on the hotel’s uploaded forecast, assessed separately from the system's projected revenue."),
  rev_st2y FLOAT64 OPTIONS(description="Total room revenue on the books as of two years ago"),
  rev_st19 FLOAT64 OPTIONS(description="Total room revenue on the books as of the same time in 2019"),
  arrivals INT64 OPTIONS(description="The total number of arrivals and the guests or bookings scheduled to check in within the defined period."),
  arrivals_py INT64 OPTIONS(description="The total number of arrivals and the guests or bookings scheduled to check in within the defined period."),
  projected_rms FLOAT64 OPTIONS(description="Projected room nights based on the hotel’s uploaded forecast, assessed separately from the system's projected room nights."),
  projected_rms_py FLOAT64 OPTIONS(description="Projected room nights based on the hotel’s uploaded forecast, assessed separately from the system's projected room nights."),
  departures INT64 OPTIONS(description="The total number of departures and the guests or bookings scheduled to check out within the defined period."),
  departures_py INT64 OPTIONS(description="The total number of departures and the guests or bookings scheduled to check out within the defined period."),
  no_show INT64 OPTIONS(description="Total No-Shows and refers to guests with confirmed reservations who neither arrived nor canceled their booking restuling in lost occupancy and missed revenue opportunities."),
  no_show_py INT64 OPTIONS(description="Total No-Shows and refers to guests with confirmed reservations who neither arrived nor canceled their booking restuling in lost occupancy and missed revenue opportunities."),
  cx INT64 OPTIONS(description="The total number of reservations canceled during a given time frame. This includes all cancellations, regardless of when the bookings were initially made or the intended stay dates."),
  cx_py INT64 OPTIONS(description="The total number of reservations canceled during a given time frame. This includes all cancellations, regardless of when the bookings were initially made or the intended stay dates."),
  bgt_rms FLOAT64 OPTIONS(description="Total budgeted room nights"),
  bgt_rms_py FLOAT64 OPTIONS(description="Total budgeted room nights"),
  bgt_rev FLOAT64 OPTIONS(description="Total budgeted room revenue"),
  bgt_rev_py FLOAT64 OPTIONS(description="Total budgeted room revenue"),
  segment_code STRING OPTIONS(description="Filters values for consumed revenue, room nights, and other metrics based on the Market Segment. These segments are categorized by shared characteristics such as the type of rate, room type, and the booking channel used by the guest."),
  segment_sort INT64 OPTIONS(description="Filters data for consumed revenue, room nights, and other essential metrics at a specific point in time."),
  segment_group STRING OPTIONS(description="Filters values for consumed revenue, room nights, and other key metrics according to the Market Segment Group. This group represents the broadest combination of market segments, categorized into Transient, Group, Contract, and Complimentary"),
  segment_group_code STRING OPTIONS(description="Filters values for consumed revenue, room nights, and other key metrics according to the Market Segment Group. This group represents the broadest combination of market segments, categorized into Transient, Group, Contract, and Complimentary"),
  finance_segment STRING OPTIONS(description="Filters values for consumed revenue, room nights, and other metrics based on the Finance Market Segment"),
  snapshot_date DATE OPTIONS(description="Filters the date in which the data was collected."),
  ingested_timestamp TIMESTAMP OPTIONS(description="Datetime of data ingestion"),
  sent_to_big_query BOOL OPTIONS(description="Sent to big query"),
  date_sent_to_big_query TIMESTAMP OPTIONS(description="Date when the data was sent to biq query")
)
PARTITION BY stay_date
CLUSTER BY property_code, snapshot_date
OPTIONS(
  partition_expiration_days=60.0
);