CREATE TABLE `devrebel-big-query-database.dev_hotel_analytics.snap_pace_segment`
(
  snapshot_date DATE OPTIONS(description="The date when the booking data was recorded."),
  stay_date DATE OPTIONS(description="The date for which the booking and revenue data applies."),
  property_code STRING OPTIONS(description="A unique identifier for the hotel property."),
  property_name STRING OPTIONS(description="The name of the hotel property."),
  segment STRING OPTIONS(description="The market segment associated with the booking data."),
  rooms_otb INT64 OPTIONS(description="The number of rooms on the books for the stay date."),
  rooms_stly INT64 OPTIONS(description="The number of rooms on the books for the stay date at the same time last year."),
  rooms_st2y INT64 OPTIONS(description="The number of rooms on the books for the stay date at the same time two years ago."),
  rooms_ly_actual INT64 OPTIONS(description="The actual number of rooms occupied for the stay date in the previous year."),
  rev_otb FLOAT64 OPTIONS(description="The revenue on the books for the stay date."),
  rev_stly FLOAT64 OPTIONS(description="The revenue on the books for the stay date at the same time last year."),
  rev_st2y FLOAT64 OPTIONS(description="The revenue on the books for the stay date at the same time two years ago."),
  rev_ly_actual FLOAT64 OPTIONS(description="The actual revenue generated for the stay date in the previous year."),
  rms_rooms_forecast INT64 OPTIONS(description="The rooms forecast generated by the revenue management system."),
  rms_rev_forecast FLOAT64 OPTIONS(description="The revenue forecast generated by the revenue management system."),
  rooms_forecast INT64 OPTIONS(description="The overall rooms forecast for the stay date."),
  rev_forecast FLOAT64 OPTIONS(description="The overall revenue forecast for the stay date."),
  rooms_budget INT64 OPTIONS(description="The budgeted number of rooms for the stay date."),
  rev_budget FLOAT64 OPTIONS(description="The budgeted revenue for the stay date."),
  cancelled_rooms INT64 OPTIONS(description="The number of rooms that have been cancelled for the stay date."),
  cancelled_rooms_ly_actual INT64 OPTIONS(description="The actual number of cancelled rooms for the stay date in the previous year."),
  noshow_rooms INT64 OPTIONS(description="The number of rooms that were no-shows for the stay date."),
  noshow_rooms_ly_actual INT64 OPTIONS(description="The actual number of no-show rooms for the stay date in the previous year.")
)
PARTITION BY snapshot_date
CLUSTER BY stay_date, segment
OPTIONS(
  description="This table tracks hotel booking and revenue performance over time. It provides a historical view of key metrics for different market segments. The table supports analysis of booking pace, revenue trends, and forecast accuracy. It enables comparisons against prior years and budget targets.",
  labels=[("dataplex-data-documentation-published-location", "us-central1"), ("dataplex-data-documentation-published-project", "devrebel-big-query-database"), ("dataplex-data-documentation-published-scan", "ac2cfa749-100d-457f-b11b-145aaba255d3")]
);