CREATE TABLE `devrebel-big-query-database.dev_hotel_analytics.vw_pace_roomtype_change_by_period_current`
(
  snapshot_date DATE OPTIONS(description="The date on which the data snapshot was taken."),
  stay_month DATE OPTIONS(description="The month for which the stay data is relevant."),
  stay_date DATE OPTIONS(description="The specific date for which the stay data is relevant."),
  property_code STRING OPTIONS(description="A unique identifier for the hotel property."),
  property_name STRING OPTIONS(description="The name of the hotel property."),
  available_rooms__commissioner_suite INT64 OPTIONS(description="The number of available Commissioner Suite rooms."),
  available_rooms__deluxe_king INT64 OPTIONS(description="The number of available Deluxe King rooms."),
  available_rooms__foundation_king INT64 OPTIONS(description="The number of available Foundation King rooms."),
  available_rooms__foundation_king_ada INT64 OPTIONS(description="The number of available ADA-compliant Foundation King rooms."),
  available_rooms__foundation_two_queen INT64 OPTIONS(description="The number of available Foundation Two Queen rooms."),
  available_rooms__junior_suite INT64 OPTIONS(description="The number of available Junior Suite rooms."),
  available_rooms__king_guestroom INT64 OPTIONS(description="The number of available King Guestroom rooms."),
  available_rooms__secretary_suite INT64 OPTIONS(description="The number of available Secretary Suite rooms."),
  available_rooms__two_queen_guestroom INT64 OPTIONS(description="The number of available Two Queen Guestroom rooms."),
  available_rooms__two_queen_guestroom_ada INT64 OPTIONS(description="The number of available ADA-compliant Two Queen Guestroom rooms."),
  rooms_otb__commissioner_suite INT64 OPTIONS(description="The number of Commissioner Suite rooms on the books for the current period."),
  rooms_otb__deluxe_king INT64 OPTIONS(description="The number of Deluxe King rooms on the books for the current period."),
  rooms_otb__foundation_king INT64 OPTIONS(description="The number of Foundation King rooms on the books for the current period."),
  rooms_otb__foundation_king_ada INT64 OPTIONS(description="The number of ADA-compliant Foundation King rooms on the books for the current period."),
  rooms_otb__foundation_two_queen INT64 OPTIONS(description="The number of Foundation Two Queen rooms on the books for the current period."),
  rooms_otb__junior_suite INT64 OPTIONS(description="The number of Junior Suite rooms on the books for the current period."),
  rooms_otb__king_guestroom INT64 OPTIONS(description="The number of King Guestroom rooms on the books for the current period."),
  rooms_otb__secretary_suite INT64 OPTIONS(description="The number of Secretary Suite rooms on the books for the current period."),
  rooms_otb__two_queen_guestroom INT64 OPTIONS(description="The number of Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb__two_queen_guestroom_ada INT64 OPTIONS(description="The number of ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rooms_stly__commissioner_suite INT64 OPTIONS(description="The number of Commissioner Suite rooms on the books for the same period last year."),
  rooms_stly__deluxe_king INT64 OPTIONS(description="The number of Deluxe King rooms on the books for the same period last year."),
  rooms_stly__foundation_king INT64 OPTIONS(description="The number of Foundation King rooms on the books for the same period last year."),
  rooms_stly__foundation_king_ada INT64 OPTIONS(description="The number of ADA-compliant Foundation King rooms on the books for the same period last year."),
  rooms_stly__foundation_two_queen INT64 OPTIONS(description="The number of Foundation Two Queen rooms on the books for the same period last year."),
  rooms_stly__junior_suite INT64 OPTIONS(description="The number of Junior Suite rooms on the books for the same period last year."),
  rooms_stly__king_guestroom INT64 OPTIONS(description="The number of King Guestroom rooms on the books for the same period last year."),
  rooms_stly__secretary_suite INT64 OPTIONS(description="The number of Secretary Suite rooms on the books for the same period last year."),
  rooms_stly__two_queen_guestroom INT64 OPTIONS(description="The number of Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly__two_queen_guestroom_ada INT64 OPTIONS(description="The number of ADA-compliant Two Queen Guestroom rooms on the books for the same period last year."),
  rev_otb__commissioner_suite FLOAT64 OPTIONS(description="The revenue from Commissioner Suite rooms on the books for the current period."),
  rev_otb__deluxe_king FLOAT64 OPTIONS(description="The revenue from Deluxe King rooms on the books for the current period."),
  rev_otb__foundation_king FLOAT64 OPTIONS(description="The revenue from Foundation King rooms on the books for the current period."),
  rev_otb__foundation_king_ada FLOAT64 OPTIONS(description="The revenue from ADA-compliant Foundation King rooms on the books for the current period."),
  rev_otb__foundation_two_queen FLOAT64 OPTIONS(description="The revenue from Foundation Two Queen rooms on the books for the current period."),
  rev_otb__junior_suite FLOAT64 OPTIONS(description="The revenue from Junior Suite rooms on the books for the current period."),
  rev_otb__king_guestroom FLOAT64 OPTIONS(description="The revenue from King Guestroom rooms on the books for the current period."),
  rev_otb__secretary_suite FLOAT64 OPTIONS(description="The revenue from Secretary Suite rooms on the books for the current period."),
  rev_otb__two_queen_guestroom FLOAT64 OPTIONS(description="The revenue from Two Queen Guestroom rooms on the books for the current period."),
  rev_otb__two_queen_guestroom_ada FLOAT64 OPTIONS(description="The revenue from ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rev_stly__commissioner_suite FLOAT64 OPTIONS(description="The revenue from Commissioner Suite rooms on the books for the same period last year."),
  rev_stly__deluxe_king FLOAT64 OPTIONS(description="The revenue from Deluxe King rooms on the books for the same period last year."),
  rev_stly__foundation_king FLOAT64 OPTIONS(description="The revenue from Foundation King rooms on the books for the same period last year."),
  rev_stly__foundation_king_ada FLOAT64 OPTIONS(description="The revenue from ADA-compliant Foundation King rooms on the books for the same period last year."),
  rev_stly__foundation_two_queen FLOAT64 OPTIONS(description="The revenue from Foundation Two Queen rooms on the books for the same period last year."),
  rev_stly__junior_suite FLOAT64 OPTIONS(description="The revenue from Junior Suite rooms on the books for the same period last year."),
  rev_stly__king_guestroom FLOAT64 OPTIONS(description="The revenue from King Guestroom rooms on the books for the same period last year."),
  rev_stly__secretary_suite FLOAT64 OPTIONS(description="The revenue from Secretary Suite rooms on the books for the same period last year."),
  rev_stly__two_queen_guestroom FLOAT64 OPTIONS(description="The revenue from Two Queen Guestroom rooms on the books for the same period last year."),
  rev_stly__two_queen_guestroom_ada FLOAT64 OPTIONS(description="The revenue from ADA-compliant Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_otb_chg_001_day__commissioner_suite INT64 OPTIONS(description="The 1-day change in Commissioner Suite rooms on the books for the current period."),
  rooms_otb_chg_001_day__deluxe_king INT64 OPTIONS(description="The 1-day change in Deluxe King rooms on the books for the current period."),
  rooms_otb_chg_001_day__foundation_king INT64 OPTIONS(description="The 1-day change in Foundation King rooms on the books for the current period."),
  rooms_otb_chg_001_day__foundation_king_ada INT64 OPTIONS(description="The 1-day change in ADA-compliant Foundation King rooms on the books for the current period."),
  rooms_otb_chg_001_day__foundation_two_queen INT64 OPTIONS(description="The 1-day change in Foundation Two Queen rooms on the books for the current period."),
  rooms_otb_chg_001_day__junior_suite INT64 OPTIONS(description="The 1-day change in Junior Suite rooms on the books for the current period."),
  rooms_otb_chg_001_day__king_guestroom INT64 OPTIONS(description="The 1-day change in King Guestroom rooms on the books for the current period."),
  rooms_otb_chg_001_day__secretary_suite INT64 OPTIONS(description="The 1-day change in Secretary Suite rooms on the books for the current period."),
  rooms_otb_chg_001_day__two_queen_guestroom INT64 OPTIONS(description="The 1-day change in Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_001_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 1-day change in ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_003_day__commissioner_suite INT64 OPTIONS(description="The 3-day change in Commissioner Suite rooms on the books for the current period."),
  rooms_otb_chg_003_day__deluxe_king INT64 OPTIONS(description="The 3-day change in Deluxe King rooms on the books for the current period."),
  rooms_otb_chg_003_day__foundation_king INT64 OPTIONS(description="The 3-day change in Foundation King rooms on the books for the current period."),
  rooms_otb_chg_003_day__foundation_king_ada INT64 OPTIONS(description="The 3-day change in ADA-compliant Foundation King rooms on the books for the current period."),
  rooms_otb_chg_003_day__foundation_two_queen INT64 OPTIONS(description="The 3-day change in Foundation Two Queen rooms on the books for the current period."),
  rooms_otb_chg_003_day__junior_suite INT64 OPTIONS(description="The 3-day change in Junior Suite rooms on the books for the current period."),
  rooms_otb_chg_003_day__king_guestroom INT64 OPTIONS(description="The 3-day change in King Guestroom rooms on the books for the current period."),
  rooms_otb_chg_003_day__secretary_suite INT64 OPTIONS(description="The 3-day change in Secretary Suite rooms on the books for the current period."),
  rooms_otb_chg_003_day__two_queen_guestroom INT64 OPTIONS(description="The 3-day change in Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_003_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 3-day change in ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_007_day__commissioner_suite INT64 OPTIONS(description="The 7-day change in Commissioner Suite rooms on the books for the current period."),
  rooms_otb_chg_007_day__deluxe_king INT64 OPTIONS(description="The 7-day change in Deluxe King rooms on the books for the current period."),
  rooms_otb_chg_007_day__foundation_king INT64 OPTIONS(description="The 7-day change in Foundation King rooms on the books for the current period."),
  rooms_otb_chg_007_day__foundation_king_ada INT64 OPTIONS(description="The 7-day change in ADA-compliant Foundation King rooms on the books for the current period."),
  rooms_otb_chg_007_day__foundation_two_queen INT64 OPTIONS(description="The 7-day change in Foundation Two Queen rooms on the books for the current period."),
  rooms_otb_chg_007_day__junior_suite INT64 OPTIONS(description="The 7-day change in Junior Suite rooms on the books for the current period."),
  rooms_otb_chg_007_day__king_guestroom INT64 OPTIONS(description="The 7-day change in King Guestroom rooms on the books for the current period."),
  rooms_otb_chg_007_day__secretary_suite INT64 OPTIONS(description="The 7-day change in Secretary Suite rooms on the books for the current period."),
  rooms_otb_chg_007_day__two_queen_guestroom INT64 OPTIONS(description="The 7-day change in Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_007_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 7-day change in ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_014_day__commissioner_suite INT64 OPTIONS(description="The 14-day change in Commissioner Suite rooms on the books for the current period."),
  rooms_otb_chg_014_day__deluxe_king INT64 OPTIONS(description="The 14-day change in Deluxe King rooms on the books for the current period."),
  rooms_otb_chg_014_day__foundation_king INT64 OPTIONS(description="The 14-day change in Foundation King rooms on the books for the current period."),
  rooms_otb_chg_014_day__foundation_king_ada INT64 OPTIONS(description="The 14-day change in ADA-compliant Foundation King rooms on the books for the current period."),
  rooms_otb_chg_014_day__foundation_two_queen INT64 OPTIONS(description="The 14-day change in Foundation Two Queen rooms on the books for the current period."),
  rooms_otb_chg_014_day__junior_suite INT64 OPTIONS(description="The 14-day change in Junior Suite rooms on the books for the current period."),
  rooms_otb_chg_014_day__king_guestroom INT64 OPTIONS(description="The 14-day change in King Guestroom rooms on the books for the current period."),
  rooms_otb_chg_014_day__secretary_suite INT64 OPTIONS(description="The 14-day change in Secretary Suite rooms on the books for the current period."),
  rooms_otb_chg_014_day__two_queen_guestroom INT64 OPTIONS(description="The 14-day change in Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_014_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 14-day change in ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_021_day__commissioner_suite INT64 OPTIONS(description="The 21-day change in Commissioner Suite rooms on the books for the current period."),
  rooms_otb_chg_021_day__deluxe_king INT64 OPTIONS(description="The 21-day change in Deluxe King rooms on the books for the current period."),
  rooms_otb_chg_021_day__foundation_king INT64 OPTIONS(description="The 21-day change in Foundation King rooms on the books for the current period."),
  rooms_otb_chg_021_day__foundation_king_ada INT64 OPTIONS(description="The 21-day change in ADA-compliant Foundation King rooms on the books for the current period."),
  rooms_otb_chg_021_day__foundation_two_queen INT64 OPTIONS(description="The 21-day change in Foundation Two Queen rooms on the books for the current period."),
  rooms_otb_chg_021_day__junior_suite INT64 OPTIONS(description="The 21-day change in Junior Suite rooms on the books for the current period."),
  rooms_otb_chg_021_day__king_guestroom INT64 OPTIONS(description="The 21-day change in King Guestroom rooms on the books for the current period."),
  rooms_otb_chg_021_day__secretary_suite INT64 OPTIONS(description="The 21-day change in Secretary Suite rooms on the books for the current period."),
  rooms_otb_chg_021_day__two_queen_guestroom INT64 OPTIONS(description="The 21-day change in Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_021_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 21-day change in ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_030_day__commissioner_suite INT64 OPTIONS(description="The 30-day change in Commissioner Suite rooms on the books for the current period."),
  rooms_otb_chg_030_day__deluxe_king INT64 OPTIONS(description="The 30-day change in Deluxe King rooms on the books for the current period."),
  rooms_otb_chg_030_day__foundation_king INT64 OPTIONS(description="The 30-day change in Foundation King rooms on the books for the current period."),
  rooms_otb_chg_030_day__foundation_king_ada INT64 OPTIONS(description="The 30-day change in ADA-compliant Foundation King rooms on the books for the current period."),
  rooms_otb_chg_030_day__foundation_two_queen INT64 OPTIONS(description="The 30-day change in Foundation Two Queen rooms on the books for the current period."),
  rooms_otb_chg_030_day__junior_suite INT64 OPTIONS(description="The 30-day change in Junior Suite rooms on the books for the current period."),
  rooms_otb_chg_030_day__king_guestroom INT64 OPTIONS(description="The 30-day change in King Guestroom rooms on the books for the current period."),
  rooms_otb_chg_030_day__secretary_suite INT64 OPTIONS(description="The 30-day change in Secretary Suite rooms on the books for the current period."),
  rooms_otb_chg_030_day__two_queen_guestroom INT64 OPTIONS(description="The 30-day change in Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_030_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 30-day change in ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_060_day__commissioner_suite INT64 OPTIONS(description="The 60-day change in Commissioner Suite rooms on the books for the current period."),
  rooms_otb_chg_060_day__deluxe_king INT64 OPTIONS(description="The 60-day change in Deluxe King rooms on the books for the current period."),
  rooms_otb_chg_060_day__foundation_king INT64 OPTIONS(description="The 60-day change in Foundation King rooms on the books for the current period."),
  rooms_otb_chg_060_day__foundation_king_ada INT64 OPTIONS(description="The 60-day change in ADA-compliant Foundation King rooms on the books for the current period."),
  rooms_otb_chg_060_day__foundation_two_queen INT64 OPTIONS(description="The 60-day change in Foundation Two Queen rooms on the books for the current period."),
  rooms_otb_chg_060_day__junior_suite INT64 OPTIONS(description="The 60-day change in Junior Suite rooms on the books for the current period."),
  rooms_otb_chg_060_day__king_guestroom INT64 OPTIONS(description="The 60-day change in King Guestroom rooms on the books for the current period."),
  rooms_otb_chg_060_day__secretary_suite INT64 OPTIONS(description="The 60-day change in Secretary Suite rooms on the books for the current period."),
  rooms_otb_chg_060_day__two_queen_guestroom INT64 OPTIONS(description="The 60-day change in Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_060_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 60-day change in ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_090_day__commissioner_suite INT64 OPTIONS(description="The 90-day change in Commissioner Suite rooms on the books for the current period."),
  rooms_otb_chg_090_day__deluxe_king INT64 OPTIONS(description="The 90-day change in Deluxe King rooms on the books for the current period."),
  rooms_otb_chg_090_day__foundation_king INT64 OPTIONS(description="The 90-day change in Foundation King rooms on the books for the current period."),
  rooms_otb_chg_090_day__foundation_king_ada INT64 OPTIONS(description="The 90-day change in ADA-compliant Foundation King rooms on the books for the current period."),
  rooms_otb_chg_090_day__foundation_two_queen INT64 OPTIONS(description="The 90-day change in Foundation Two Queen rooms on the books for the current period."),
  rooms_otb_chg_090_day__junior_suite INT64 OPTIONS(description="The 90-day change in Junior Suite rooms on the books for the current period."),
  rooms_otb_chg_090_day__king_guestroom INT64 OPTIONS(description="The 90-day change in King Guestroom rooms on the books for the current period."),
  rooms_otb_chg_090_day__secretary_suite INT64 OPTIONS(description="The 90-day change in Secretary Suite rooms on the books for the current period."),
  rooms_otb_chg_090_day__two_queen_guestroom INT64 OPTIONS(description="The 90-day change in Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_090_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 90-day change in ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_120_day__commissioner_suite INT64 OPTIONS(description="The 120-day change in Commissioner Suite rooms on the books for the current period."),
  rooms_otb_chg_120_day__deluxe_king INT64 OPTIONS(description="The 120-day change in Deluxe King rooms on the books for the current period."),
  rooms_otb_chg_120_day__foundation_king INT64 OPTIONS(description="The 120-day change in Foundation King rooms on the books for the current period."),
  rooms_otb_chg_120_day__foundation_king_ada INT64 OPTIONS(description="The 120-day change in ADA-compliant Foundation King rooms on the books for the current period."),
  rooms_otb_chg_120_day__foundation_two_queen INT64 OPTIONS(description="The 120-day change in Foundation Two Queen rooms on the books for the current period."),
  rooms_otb_chg_120_day__junior_suite INT64 OPTIONS(description="The 120-day change in Junior Suite rooms on the books for the current period."),
  rooms_otb_chg_120_day__king_guestroom INT64 OPTIONS(description="The 120-day change in King Guestroom rooms on the books for the current period."),
  rooms_otb_chg_120_day__secretary_suite INT64 OPTIONS(description="The 120-day change in Secretary Suite rooms on the books for the current period."),
  rooms_otb_chg_120_day__two_queen_guestroom INT64 OPTIONS(description="The 120-day change in Two Queen Guestroom rooms on the books for the current period."),
  rooms_otb_chg_120_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 120-day change in ADA-compliant Two Queen Guestroom rooms on the books for the current period."),
  rooms_stly_chg_001_day__commissioner_suite INT64 OPTIONS(description="The 1-day change in Commissioner Suite rooms on the books for the same period last year."),
  rooms_stly_chg_001_day__deluxe_king INT64 OPTIONS(description="The 1-day change in Deluxe King rooms on the books for the same period last year."),
  rooms_stly_chg_001_day__foundation_king INT64 OPTIONS(description="The 1-day change in Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_001_day__foundation_king_ada INT64 OPTIONS(description="The 1-day change in ADA-compliant Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_001_day__foundation_two_queen INT64 OPTIONS(description="The 1-day change in Foundation Two Queen rooms on the books for the same period last year."),
  rooms_stly_chg_001_day__junior_suite INT64 OPTIONS(description="The 1-day change in Junior Suite rooms on the books for the same period last year."),
  rooms_stly_chg_001_day__king_guestroom INT64 OPTIONS(description="The 1-day change in King Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_001_day__secretary_suite INT64 OPTIONS(description="The 1-day change in Secretary Suite rooms on the books for the same period last year."),
  rooms_stly_chg_001_day__two_queen_guestroom INT64 OPTIONS(description="The 1-day change in Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_001_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 1-day change in ADA-compliant Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_003_day__commissioner_suite INT64 OPTIONS(description="The 3-day change in Commissioner Suite rooms on the books for the same period last year."),
  rooms_stly_chg_003_day__deluxe_king INT64 OPTIONS(description="The 3-day change in Deluxe King rooms on the books for the same period last year."),
  rooms_stly_chg_003_day__foundation_king INT64 OPTIONS(description="The 3-day change in Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_003_day__foundation_king_ada INT64 OPTIONS(description="The 3-day change in ADA-compliant Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_003_day__foundation_two_queen INT64 OPTIONS(description="The 3-day change in Foundation Two Queen rooms on the books for the same period last year."),
  rooms_stly_chg_003_day__junior_suite INT64 OPTIONS(description="The 3-day change in Junior Suite rooms on the books for the same period last year."),
  rooms_stly_chg_003_day__king_guestroom INT64 OPTIONS(description="The 3-day change in King Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_003_day__secretary_suite INT64 OPTIONS(description="The 3-day change in Secretary Suite rooms on the books for the same period last year."),
  rooms_stly_chg_003_day__two_queen_guestroom INT64 OPTIONS(description="The 3-day change in Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_003_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 3-day change in ADA-compliant Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_007_day__commissioner_suite INT64 OPTIONS(description="The 7-day change in Commissioner Suite rooms on the books for the same period last year."),
  rooms_stly_chg_007_day__deluxe_king INT64 OPTIONS(description="The 7-day change in Deluxe King rooms on the books for the same period last year."),
  rooms_stly_chg_007_day__foundation_king INT64 OPTIONS(description="The 7-day change in Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_007_day__foundation_king_ada INT64 OPTIONS(description="The 7-day change in ADA-compliant Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_007_day__foundation_two_queen INT64 OPTIONS(description="The 7-day change in Foundation Two Queen rooms on the books for the same period last year."),
  rooms_stly_chg_007_day__junior_suite INT64 OPTIONS(description="The 7-day change in Junior Suite rooms on the books for the same period last year."),
  rooms_stly_chg_007_day__king_guestroom INT64 OPTIONS(description="The 7-day change in King Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_007_day__secretary_suite INT64 OPTIONS(description="The 7-day change in Secretary Suite rooms on the books for the same period last year."),
  rooms_stly_chg_007_day__two_queen_guestroom INT64 OPTIONS(description="The 7-day change in Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_007_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 7-day change in ADA-compliant Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_014_day__commissioner_suite INT64 OPTIONS(description="The 14-day change in Commissioner Suite rooms on the books for the same period last year."),
  rooms_stly_chg_014_day__deluxe_king INT64 OPTIONS(description="The 14-day change in Deluxe King rooms on the books for the same period last year."),
  rooms_stly_chg_014_day__foundation_king INT64 OPTIONS(description="The 14-day change in Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_014_day__foundation_king_ada INT64 OPTIONS(description="The 14-day change in ADA-compliant Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_014_day__foundation_two_queen INT64 OPTIONS(description="The 14-day change in Foundation Two Queen rooms on the books for the same period last year."),
  rooms_stly_chg_014_day__junior_suite INT64 OPTIONS(description="The 14-day change in Junior Suite rooms on the books for the same period last year."),
  rooms_stly_chg_014_day__king_guestroom INT64 OPTIONS(description="The 14-day change in King Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_014_day__secretary_suite INT64 OPTIONS(description="The 14-day change in Secretary Suite rooms on the books for the same period last year."),
  rooms_stly_chg_014_day__two_queen_guestroom INT64 OPTIONS(description="The 14-day change in Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_014_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 14-day change in ADA-compliant Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_021_day__commissioner_suite INT64 OPTIONS(description="The 21-day change in Commissioner Suite rooms on the books for the same period last year."),
  rooms_stly_chg_021_day__deluxe_king INT64 OPTIONS(description="The 21-day change in Deluxe King rooms on the books for the same period last year."),
  rooms_stly_chg_021_day__foundation_king INT64 OPTIONS(description="The 21-day change in Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_021_day__foundation_king_ada INT64 OPTIONS(description="The 21-day change in ADA-compliant Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_021_day__foundation_two_queen INT64 OPTIONS(description="The 21-day change in Foundation Two Queen rooms on the books for the same period last year."),
  rooms_stly_chg_021_day__junior_suite INT64 OPTIONS(description="The 21-day change in Junior Suite rooms on the books for the same period last year."),
  rooms_stly_chg_021_day__king_guestroom INT64 OPTIONS(description="The 21-day change in King Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_021_day__secretary_suite INT64 OPTIONS(description="The 21-day change in Secretary Suite rooms on the books for the same period last year."),
  rooms_stly_chg_021_day__two_queen_guestroom INT64 OPTIONS(description="The 21-day change in Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_021_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 21-day change in ADA-compliant Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_030_day__commissioner_suite INT64 OPTIONS(description="The 30-day change in Commissioner Suite rooms on the books for the same period last year."),
  rooms_stly_chg_030_day__deluxe_king INT64 OPTIONS(description="The 30-day change in Deluxe King rooms on the books for the same period last year."),
  rooms_stly_chg_030_day__foundation_king INT64 OPTIONS(description="The 30-day change in Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_030_day__foundation_king_ada INT64 OPTIONS(description="The 30-day change in ADA-compliant Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_030_day__foundation_two_queen INT64 OPTIONS(description="The 30-day change in Foundation Two Queen rooms on the books for the same period last year."),
  rooms_stly_chg_030_day__junior_suite INT64 OPTIONS(description="The 30-day change in Junior Suite rooms on the books for the same period last year."),
  rooms_stly_chg_030_day__king_guestroom INT64 OPTIONS(description="The 30-day change in King Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_030_day__secretary_suite INT64 OPTIONS(description="The 30-day change in Secretary Suite rooms on the books for the same period last year."),
  rooms_stly_chg_030_day__two_queen_guestroom INT64 OPTIONS(description="The 30-day change in Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_030_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 30-day change in ADA-compliant Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_060_day__commissioner_suite INT64 OPTIONS(description="The 60-day change in Commissioner Suite rooms on the books for the same period last year."),
  rooms_stly_chg_060_day__deluxe_king INT64 OPTIONS(description="The 60-day change in Deluxe King rooms on the books for the same period last year."),
  rooms_stly_chg_060_day__foundation_king INT64 OPTIONS(description="The 60-day change in Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_060_day__foundation_king_ada INT64 OPTIONS(description="The 60-day change in ADA-compliant Foundation King rooms on the books for the same period last year."),
  rooms_stly_chg_060_day__foundation_two_queen INT64 OPTIONS(description="The 60-day change in Foundation Two Queen rooms on the books for the same period last year."),
  rooms_stly_chg_060_day__junior_suite INT64 OPTIONS(description="The 60-day change in Junior Suite rooms on the books for the same period last year."),
  rooms_stly_chg_060_day__king_guestroom INT64 OPTIONS(description="The 60-day change in King Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_060_day__secretary_suite INT64 OPTIONS(description="The 60-day change in Secretary Suite rooms on the books for the same period last year."),
  rooms_stly_chg_060_day__two_queen_guestroom INT64 OPTIONS(description="The 60-day change in Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_060_day__two_queen_guestroom_ada INT64 OPTIONS(description="The 60-day change in ADA-compliant Two Queen Guestroom rooms on the books for the same period last year."),
  rooms_stly_chg_090_day__commissioner_suite INT64 OPTIONS(description="The 90-day change in Commissioner Suite rooms on the books for the same period last year."),
  rooms_stly_chg_090_day__deluxe_king INT64 OPTIONS(description="The 90-day change in Deluxe King rooms on the books for the same period last year"),
  rooms_stly_chg_090_day__foundation_king INT64,
  rooms_stly_chg_090_day__foundation_king_ada INT64,
  rooms_stly_chg_090_day__foundation_two_queen INT64,
  rooms_stly_chg_090_day__junior_suite INT64,
  rooms_stly_chg_090_day__king_guestroom INT64,
  rooms_stly_chg_090_day__secretary_suite INT64,
  rooms_stly_chg_090_day__two_queen_guestroom INT64,
  rooms_stly_chg_090_day__two_queen_guestroom_ada INT64,
  rooms_stly_chg_120_day__commissioner_suite INT64,
  rooms_stly_chg_120_day__deluxe_king INT64,
  rooms_stly_chg_120_day__foundation_king INT64,
  rooms_stly_chg_120_day__foundation_king_ada INT64,
  rooms_stly_chg_120_day__foundation_two_queen INT64,
  rooms_stly_chg_120_day__junior_suite INT64,
  rooms_stly_chg_120_day__king_guestroom INT64,
  rooms_stly_chg_120_day__secretary_suite INT64,
  rooms_stly_chg_120_day__two_queen_guestroom INT64,
  rooms_stly_chg_120_day__two_queen_guestroom_ada INT64,
  rev_otb_chg_001_day__commissioner_suite FLOAT64,
  rev_otb_chg_001_day__deluxe_king FLOAT64,
  rev_otb_chg_001_day__foundation_king FLOAT64,
  rev_otb_chg_001_day__foundation_king_ada FLOAT64,
  rev_otb_chg_001_day__foundation_two_queen FLOAT64,
  rev_otb_chg_001_day__junior_suite FLOAT64,
  rev_otb_chg_001_day__king_guestroom FLOAT64,
  rev_otb_chg_001_day__secretary_suite FLOAT64,
  rev_otb_chg_001_day__two_queen_guestroom FLOAT64,
  rev_otb_chg_001_day__two_queen_guestroom_ada FLOAT64,
  rev_otb_chg_003_day__commissioner_suite FLOAT64,
  rev_otb_chg_003_day__deluxe_king FLOAT64,
  rev_otb_chg_003_day__foundation_king FLOAT64,
  rev_otb_chg_003_day__foundation_king_ada FLOAT64,
  rev_otb_chg_003_day__foundation_two_queen FLOAT64,
  rev_otb_chg_003_day__junior_suite FLOAT64,
  rev_otb_chg_003_day__king_guestroom FLOAT64,
  rev_otb_chg_003_day__secretary_suite FLOAT64,
  rev_otb_chg_003_day__two_queen_guestroom FLOAT64,
  rev_otb_chg_003_day__two_queen_guestroom_ada FLOAT64,
  rev_otb_chg_007_day__commissioner_suite FLOAT64,
  rev_otb_chg_007_day__deluxe_king FLOAT64,
  rev_otb_chg_007_day__foundation_king FLOAT64,
  rev_otb_chg_007_day__foundation_king_ada FLOAT64,
  rev_otb_chg_007_day__foundation_two_queen FLOAT64,
  rev_otb_chg_007_day__junior_suite FLOAT64,
  rev_otb_chg_007_day__king_guestroom FLOAT64,
  rev_otb_chg_007_day__secretary_suite FLOAT64,
  rev_otb_chg_007_day__two_queen_guestroom FLOAT64,
  rev_otb_chg_007_day__two_queen_guestroom_ada FLOAT64,
  rev_otb_chg_014_day__commissioner_suite FLOAT64,
  rev_otb_chg_014_day__deluxe_king FLOAT64,
  rev_otb_chg_014_day__foundation_king FLOAT64,
  rev_otb_chg_014_day__foundation_king_ada FLOAT64,
  rev_otb_chg_014_day__foundation_two_queen FLOAT64,
  rev_otb_chg_014_day__junior_suite FLOAT64,
  rev_otb_chg_014_day__king_guestroom FLOAT64,
  rev_otb_chg_014_day__secretary_suite FLOAT64,
  rev_otb_chg_014_day__two_queen_guestroom FLOAT64,
  rev_otb_chg_014_day__two_queen_guestroom_ada FLOAT64,
  rev_otb_chg_021_day__commissioner_suite FLOAT64,
  rev_otb_chg_021_day__deluxe_king FLOAT64,
  rev_otb_chg_021_day__foundation_king FLOAT64,
  rev_otb_chg_021_day__foundation_king_ada FLOAT64,
  rev_otb_chg_021_day__foundation_two_queen FLOAT64,
  rev_otb_chg_021_day__junior_suite FLOAT64,
  rev_otb_chg_021_day__king_guestroom FLOAT64,
  rev_otb_chg_021_day__secretary_suite FLOAT64,
  rev_otb_chg_021_day__two_queen_guestroom FLOAT64,
  rev_otb_chg_021_day__two_queen_guestroom_ada FLOAT64,
  rev_otb_chg_030_day__commissioner_suite FLOAT64,
  rev_otb_chg_030_day__deluxe_king FLOAT64,
  rev_otb_chg_030_day__foundation_king FLOAT64,
  rev_otb_chg_030_day__foundation_king_ada FLOAT64,
  rev_otb_chg_030_day__foundation_two_queen FLOAT64,
  rev_otb_chg_030_day__junior_suite FLOAT64,
  rev_otb_chg_030_day__king_guestroom FLOAT64,
  rev_otb_chg_030_day__secretary_suite FLOAT64,
  rev_otb_chg_030_day__two_queen_guestroom FLOAT64,
  rev_otb_chg_030_day__two_queen_guestroom_ada FLOAT64,
  rev_otb_chg_060_day__commissioner_suite FLOAT64,
  rev_otb_chg_060_day__deluxe_king FLOAT64,
  rev_otb_chg_060_day__foundation_king FLOAT64,
  rev_otb_chg_060_day__foundation_king_ada FLOAT64,
  rev_otb_chg_060_day__foundation_two_queen FLOAT64,
  rev_otb_chg_060_day__junior_suite FLOAT64,
  rev_otb_chg_060_day__king_guestroom FLOAT64,
  rev_otb_chg_060_day__secretary_suite FLOAT64,
  rev_otb_chg_060_day__two_queen_guestroom FLOAT64,
  rev_otb_chg_060_day__two_queen_guestroom_ada FLOAT64,
  rev_otb_chg_090_day__commissioner_suite FLOAT64,
  rev_otb_chg_090_day__deluxe_king FLOAT64,
  rev_otb_chg_090_day__foundation_king FLOAT64,
  rev_otb_chg_090_day__foundation_king_ada FLOAT64,
  rev_otb_chg_090_day__foundation_two_queen FLOAT64,
  rev_otb_chg_090_day__junior_suite FLOAT64,
  rev_otb_chg_090_day__king_guestroom FLOAT64,
  rev_otb_chg_090_day__secretary_suite FLOAT64,
  rev_otb_chg_090_day__two_queen_guestroom FLOAT64,
  rev_otb_chg_090_day__two_queen_guestroom_ada FLOAT64,
  rev_otb_chg_120_day__commissioner_suite FLOAT64,
  rev_otb_chg_120_day__deluxe_king FLOAT64,
  rev_otb_chg_120_day__foundation_king FLOAT64,
  rev_otb_chg_120_day__foundation_king_ada FLOAT64,
  rev_otb_chg_120_day__foundation_two_queen FLOAT64,
  rev_otb_chg_120_day__junior_suite FLOAT64,
  rev_otb_chg_120_day__king_guestroom FLOAT64,
  rev_otb_chg_120_day__secretary_suite FLOAT64,
  rev_otb_chg_120_day__two_queen_guestroom FLOAT64,
  rev_otb_chg_120_day__two_queen_guestroom_ada FLOAT64,
  rev_stly_chg_001_day__commissioner_suite FLOAT64,
  rev_stly_chg_001_day__deluxe_king FLOAT64,
  rev_stly_chg_001_day__foundation_king FLOAT64,
  rev_stly_chg_001_day__foundation_king_ada FLOAT64,
  rev_stly_chg_001_day__foundation_two_queen FLOAT64,
  rev_stly_chg_001_day__junior_suite FLOAT64,
  rev_stly_chg_001_day__king_guestroom FLOAT64,
  rev_stly_chg_001_day__secretary_suite FLOAT64,
  rev_stly_chg_001_day__two_queen_guestroom FLOAT64,
  rev_stly_chg_001_day__two_queen_guestroom_ada FLOAT64,
  rev_stly_chg_003_day__commissioner_suite FLOAT64,
  rev_stly_chg_003_day__deluxe_king FLOAT64,
  rev_stly_chg_003_day__foundation_king FLOAT64,
  rev_stly_chg_003_day__foundation_king_ada FLOAT64,
  rev_stly_chg_003_day__foundation_two_queen FLOAT64,
  rev_stly_chg_003_day__junior_suite FLOAT64,
  rev_stly_chg_003_day__king_guestroom FLOAT64,
  rev_stly_chg_003_day__secretary_suite FLOAT64,
  rev_stly_chg_003_day__two_queen_guestroom FLOAT64,
  rev_stly_chg_003_day__two_queen_guestroom_ada FLOAT64,
  rev_stly_chg_007_day__commissioner_suite FLOAT64,
  rev_stly_chg_007_day__deluxe_king FLOAT64,
  rev_stly_chg_007_day__foundation_king FLOAT64,
  rev_stly_chg_007_day__foundation_king_ada FLOAT64,
  rev_stly_chg_007_day__foundation_two_queen FLOAT64,
  rev_stly_chg_007_day__junior_suite FLOAT64,
  rev_stly_chg_007_day__king_guestroom FLOAT64,
  rev_stly_chg_007_day__secretary_suite FLOAT64,
  rev_stly_chg_007_day__two_queen_guestroom FLOAT64,
  rev_stly_chg_007_day__two_queen_guestroom_ada FLOAT64,
  rev_stly_chg_014_day__commissioner_suite FLOAT64,
  rev_stly_chg_014_day__deluxe_king FLOAT64,
  rev_stly_chg_014_day__foundation_king FLOAT64,
  rev_stly_chg_014_day__foundation_king_ada FLOAT64,
  rev_stly_chg_014_day__foundation_two_queen FLOAT64,
  rev_stly_chg_014_day__junior_suite FLOAT64,
  rev_stly_chg_014_day__king_guestroom FLOAT64,
  rev_stly_chg_014_day__secretary_suite FLOAT64,
  rev_stly_chg_014_day__two_queen_guestroom FLOAT64,
  rev_stly_chg_014_day__two_queen_guestroom_ada FLOAT64,
  rev_stly_chg_021_day__commissioner_suite FLOAT64,
  rev_stly_chg_021_day__deluxe_king FLOAT64,
  rev_stly_chg_021_day__foundation_king FLOAT64,
  rev_stly_chg_021_day__foundation_king_ada FLOAT64,
  rev_stly_chg_021_day__foundation_two_queen FLOAT64,
  rev_stly_chg_021_day__junior_suite FLOAT64,
  rev_stly_chg_021_day__king_guestroom FLOAT64,
  rev_stly_chg_021_day__secretary_suite FLOAT64,
  rev_stly_chg_021_day__two_queen_guestroom FLOAT64,
  rev_stly_chg_021_day__two_queen_guestroom_ada FLOAT64,
  rev_stly_chg_030_day__commissioner_suite FLOAT64,
  rev_stly_chg_030_day__deluxe_king FLOAT64,
  rev_stly_chg_030_day__foundation_king FLOAT64,
  rev_stly_chg_030_day__foundation_king_ada FLOAT64,
  rev_stly_chg_030_day__foundation_two_queen FLOAT64,
  rev_stly_chg_030_day__junior_suite FLOAT64,
  rev_stly_chg_030_day__king_guestroom FLOAT64,
  rev_stly_chg_030_day__secretary_suite FLOAT64,
  rev_stly_chg_030_day__two_queen_guestroom FLOAT64,
  rev_stly_chg_030_day__two_queen_guestroom_ada FLOAT64,
  rev_stly_chg_060_day__commissioner_suite FLOAT64,
  rev_stly_chg_060_day__deluxe_king FLOAT64,
  rev_stly_chg_060_day__foundation_king FLOAT64,
  rev_stly_chg_060_day__foundation_king_ada FLOAT64,
  rev_stly_chg_060_day__foundation_two_queen FLOAT64,
  rev_stly_chg_060_day__junior_suite FLOAT64,
  rev_stly_chg_060_day__king_guestroom FLOAT64,
  rev_stly_chg_060_day__secretary_suite FLOAT64,
  rev_stly_chg_060_day__two_queen_guestroom FLOAT64,
  rev_stly_chg_060_day__two_queen_guestroom_ada FLOAT64,
  rev_stly_chg_090_day__commissioner_suite FLOAT64,
  rev_stly_chg_090_day__deluxe_king FLOAT64,
  rev_stly_chg_090_day__foundation_king FLOAT64,
  rev_stly_chg_090_day__foundation_king_ada FLOAT64,
  rev_stly_chg_090_day__foundation_two_queen FLOAT64,
  rev_stly_chg_090_day__junior_suite FLOAT64,
  rev_stly_chg_090_day__king_guestroom FLOAT64,
  rev_stly_chg_090_day__secretary_suite FLOAT64,
  rev_stly_chg_090_day__two_queen_guestroom FLOAT64,
  rev_stly_chg_090_day__two_queen_guestroom_ada FLOAT64,
  rev_stly_chg_120_day__commissioner_suite FLOAT64,
  rev_stly_chg_120_day__deluxe_king FLOAT64,
  rev_stly_chg_120_day__foundation_king FLOAT64,
  rev_stly_chg_120_day__foundation_king_ada FLOAT64,
  rev_stly_chg_120_day__foundation_two_queen FLOAT64,
  rev_stly_chg_120_day__junior_suite FLOAT64,
  rev_stly_chg_120_day__king_guestroom FLOAT64,
  rev_stly_chg_120_day__secretary_suite FLOAT64,
  rev_stly_chg_120_day__two_queen_guestroom FLOAT64,
  rev_stly_chg_120_day__two_queen_guestroom_ada FLOAT64
)
OPTIONS(
  description="This table provides a comprehensive view of hotel room inventory and revenue performance by room type over time. It captures daily snapshots of available rooms, rooms booked, and associated revenue for both the current period and the same period last year. The table also tracks the daily, 3-day, 7-day, 14-day, 21-day, 30-day, 60-day, 90-day, and 120-day changes in these metrics, enabling detailed pace analysis and trend identification. This data supports strategic revenue management and operational planning for hotel properties.",
  labels=[("dataplex-data-documentation-published-location", "us-central1"), ("dataplex-data-documentation-published-project", "devrebel-big-query-database"), ("dataplex-data-documentation-published-scan", "af5233557-520f-4580-b7fd-18bc340d9edc")]
);