CREATE TABLE `devrebel-big-query-database.metrics_pace.snap_property`
(
  property_code STRING OPTIONS(description="A unique identifier for each property."),
  property_name STRING OPTIONS(description="The name of the property."),
  stay_date DATE OPTIONS(description="The specific date for which the metrics are recorded."),
  special_events STRING OPTIONS(description="Information about special events occurring on the stay date."),
  special_events_ly STRING OPTIONS(description="Information about special events that occurred on the same date last year."),
  available_rooms INT64 OPTIONS(description="The total number of rooms available for booking."),
  available_rooms_ly INT64 OPTIONS(description="The total number of rooms available for booking on the same date last year."),
  rooms_otb INT64 OPTIONS(description="The number of rooms booked on the books for the stay date."),
  rooms_ly_actual INT64 OPTIONS(description="The actual number of rooms booked on the same date last year."),
  rooms_stly INT64 OPTIONS(description="The number of rooms booked on the same date two years ago."),
  rooms_st2y INT64 OPTIONS(description="The number of rooms booked on the same date three years ago."),
  rms_rooms_forecast INT64 OPTIONS(description="The forecasted number of rooms."),
  rev_otb FLOAT64 OPTIONS(description="The revenue on the books for the stay date."),
  rev_ly_actual FLOAT64 OPTIONS(description="The actual revenue on the same date last year."),
  rev_stly FLOAT64 OPTIONS(description="The revenue on the same date two years ago."),
  rev_st2y FLOAT64 OPTIONS(description="The revenue on the same date three years ago."),
  rms_rev_forecast FLOAT64 OPTIONS(description="The forecasted revenue."),
  transient_rooms_otb INT64 OPTIONS(description="The number of transient rooms booked on the books for the stay date."),
  transient_rooms_ly_actual INT64 OPTIONS(description="The actual number of transient rooms booked on the same date last year."),
  transient_rooms_stly INT64 OPTIONS(description="The number of transient rooms booked on the same date two years ago."),
  transient_rooms_st2y INT64 OPTIONS(description="The number of transient rooms booked on the same date three years ago."),
  transient_rev_otb FLOAT64 OPTIONS(description="The transient revenue on the books for the stay date."),
  transient_rev_ly_actual FLOAT64 OPTIONS(description="The actual transient revenue on the same date last year."),
  transient_rev_stly FLOAT64 OPTIONS(description="The transient revenue on the same date two years ago."),
  transient_rev_st2y FLOAT64 OPTIONS(description="The transient revenue on the same date three years ago."),
  group_rooms_otb INT64 OPTIONS(description="The number of group rooms booked on the books for the stay date."),
  group_rooms_ly_actual INT64 OPTIONS(description="The actual number of group rooms booked on the same date last year."),
  group_rooms_stly INT64 OPTIONS(description="The number of group rooms booked on the same date two years ago."),
  group_rooms_st2y INT64 OPTIONS(description="The number of group rooms booked on the same date three years ago."),
  group_rev_otb FLOAT64 OPTIONS(description="The group revenue on the books for the stay date."),
  group_rev_ly_actual FLOAT64 OPTIONS(description="The actual group revenue on the same date last year."),
  group_rev_stly FLOAT64 OPTIONS(description="The group revenue on the same date two years ago."),
  group_rev_st2y FLOAT64 OPTIONS(description="The group revenue on the same date three years ago."),
  total_demand_total INT64 OPTIONS(description="The total demand for rooms."),
  total_demand_total_ly_actual INT64 OPTIONS(description="The actual total demand for rooms on the same date last year."),
  total_demand_group INT64 OPTIONS(description="The demand for group rooms."),
  total_demand_group_ly_actual INT64 OPTIONS(description="The actual demand for group rooms on the same date last year."),
  total_demand_transient INT64 OPTIONS(description="The demand for transient rooms."),
  total_demand_transient_ly_actual INT64 OPTIONS(description="The actual demand for transient rooms on the same date last year."),
  ooo_rooms INT64 OPTIONS(description="The number of out-of-order rooms."),
  ooo_rooms_ly INT64 OPTIONS(description="The number of out-of-order rooms on the same date last year."),
  lrv FLOAT64 OPTIONS(description="The last room value."),
  wash_pct FLOAT64 OPTIONS(description="The percentage of rooms that are washed."),
  wash_pct_ly_actual FLOAT64 OPTIONS(description="The actual percentage of rooms that were washed on the same date last year."),
  bar_price FLOAT64 OPTIONS(description="The best available rate price."),
  snapshot_date DATE OPTIONS(description="The date when the data snapshot was taken.")
)
PARTITION BY snapshot_date
CLUSTER BY stay_date
OPTIONS(
  description="This table captures daily operational metrics and historical performance for various lodging establishments. It provides a snapshot of room availability, booking pace, and revenue figures. The data supports analysis of current and past performance, aiding in forecasting and strategic decision-making for individual properties. It also allows for comparison of current trends against previous years."
);