CREATE TABLE `devrebel-big-query-database.dev_hotel_sales.nihrm__BookingPostedRevenue__c`
(
  Id STRING,
  IsDeleted BOOL,
  Name STRING,
  CurrencyIsoCode STRING,
  CreatedDate TIMESTAMP,
  CreatedById STRING,
  LastModifiedDate TIMESTAMP,
  LastModifiedById STRING,
  SystemModstamp TIMESTAMP,
  nihrm__Booking__c STRING,
  nihrm__IsStayComplete__c BOOL,
  nihrm__PatternDateString__c STRING,
  nihrm__PatternDate__c DATE,
  nihrm__PostedRevenue10__c FLOAT64,
  nihrm__PostedRevenue11__c FLOAT64,
  nihrm__PostedRevenue12__c FLOAT64,
  nihrm__PostedRevenue13__c FLOAT64,
  nihrm__PostedRevenue14__c FLOAT64,
  nihrm__PostedRevenue15__c FLOAT64,
  nihrm__PostedRevenue1__c FLOAT64,
  nihrm__PostedRevenue2__c FLOAT64,
  nihrm__PostedRevenue3__c FLOAT64,
  nihrm__PostedRevenue4__c FLOAT64,
  nihrm__PostedRevenue5__c FLOAT64,
  nihrm__PostedRevenue6__c FLOAT64,
  nihrm__PostedRevenue7__c FLOAT64,
  nihrm__PostedRevenue8__c FLOAT64,
  nihrm__PostedRevenue9__c FLOAT64,
  nihrm__RevenueType__c STRING,
  nihrm__RoomBlock__c STRING,
  nihrm__TotalPostedRevenue__c FLOAT64,
  nihrm__UnknownMappingCodes__c STRING,
  nihrm__NIHRMMigrations_ExternalID__c STRING
);