CREATE TABLE `devrebel-big-query-database.dev_hotel_sales.nihrm__PackageEvent__c`
(
  Id STRING,
  IsDeleted BOOL,
  Name STRING,
  CurrencyIsoCode STRING,
  CreatedDate TIMESTAMP,
  CreatedById STRING,
  LastModifiedDate TIMESTAMP,
  LastModifiedById STRING,
  SystemModstamp TIMESTAMP,
  nihrm__Package__c STRING,
  nihrm__ApplyPackageAttendance__c BOOL,
  nihrm__CreateEvent__c BOOL,
  nihrm__EndEvents__c DATE,
  nihrm__EventClassification__c STRING,
  nihrm__EventCreateDay__c STRING,
  nihrm__Location__c STRING,
  nihrm__PackageEventPrice10__c FLOAT64,
  nihrm__PackageEventPrice11__c FLOAT64,
  nihrm__PackageEventPrice12__c FLOAT64,
  nihrm__PackageEventPrice13__c FLOAT64,
  nihrm__PackageEventPrice14__c FLOAT64,
  nihrm__PackageEventPrice15__c FLOAT64,
  nihrm__PackageEventPrice1__c FLOAT64,
  nihrm__PackageEventPrice2__c FLOAT64,
  nihrm__PackageEventPrice3__c FLOAT64,
  nihrm__PackageEventPrice4__c FLOAT64,
  nihrm__PackageEventPrice5__c FLOAT64,
  nihrm__PackageEventPrice6__c FLOAT64,
  nihrm__PackageEventPrice7__c FLOAT64,
  nihrm__PackageEventPrice8__c FLOAT64,
  nihrm__PackageEventPrice9__c FLOAT64,
  nihrm__PackageEventPriceTotal__c FLOAT64,
  nihrm__PackageIdEventClassificationIdString__c STRING,
  nihrm__StartEvents__c DATE,
  nihrm__NIHRMMigrations_ExternalID__c STRING
);