CREATE TABLE `devrebel-big-query-database.dev_hotel_sales.nihrm__RevenueClassification__c`
(
  Id STRING,
  OwnerId STRING,
  IsDeleted BOOL,
  Name STRING,
  CurrencyIsoCode STRING,
  CreatedDate TIMESTAMP,
  CreatedById STRING,
  LastModifiedDate TIMESTAMP,
  LastModifiedById STRING,
  SystemModstamp TIMESTAMP,
  LastViewedDate TIMESTAMP,
  LastReferencedDate TIMESTAMP,
  nihrm__CategoryMapping__c FLOAT64,
  nihrm__DefaultAdminCharge__c FLOAT64,
  nihrm__DefaultGratuity__c FLOAT64,
  nihrm__ExternalId__c STRING,
  nihrm__IsActive__c BOOL,
  nihrm__IsAdminChargeRevenue__c BOOL,
  nihrm__IsFunctionRoomRevenue__c BOOL,
  nihrm__IsRootClassification__c BOOL,
  nihrm__Location__c STRING,
  nihrm__MapsToCorporate__c STRING,
  nihrm__MasterSource__c STRING,
  nihrm__ParentClassification__c STRING,
  nihrm__SourceSystemExternalId__c STRING,
  nihrm__UniqueExternalId__c STRING,
  nihrm__AdminIsIncludedInInclusivePrice__c BOOL,
  nihrm__GratuityIsIncludedInInclusivePrice__c BOOL,
  nihrm__NIHRMMigrations_ExternalID__c STRING,
  nihrm__ApplyChargesToDiscPrice__c BOOL
);