CREATE TABLE `devrebel-big-query-database.dev_hotel_sales.nihrm__BookingInquiry__c`
(
  Id STRING,
  IsDeleted BOOL,
  Name STRING,
  CurrencyIsoCode STRING,
  CreatedDate TIMESTAMP,
  CreatedById STRING,
  LastModifiedDate TIMESTAMP,
  LastModifiedById STRING,
  SystemModstamp TIMESTAMP,
  nihrm__Booking__c STRING,
  nihrm__ExternalBookingId__c STRING,
  nihrm__ExternalRfpId__c STRING,
  nihrm__InquiryIdBookingId__c STRING,
  nihrm__Inquiry__c STRING,
  nihrm__IsPrimary__c BOOL,
  nihrm__Location__c STRING,
  nihrm__MbReferenceNumber__c STRING,
  nihrm__NIHRMMigrations_ExternalID__c STRING,
  nihrm__ProposalCreatedDateDisplay__c TIMESTAMP,
  nihrm__ProposalCreatedDate__c TIMESTAMP,
  nihrm__RfpChannel__c STRING,
  nihrm__RfpGuid__c STRING,
  nihrm__RfpId__c STRING,
  nihrm__RfpMilestone__c STRING,
  nihrm__RfpStatus__c STRING,
  nihrm__UniqueInquiryId__c STRING
);