CREATE OR REPLACE VIEW `aparium-dataflow.StarData.MonthlyStarYtdV` AS
WITH latest_date AS (
  SELECT
    MAX(DATE(cy, month, 1)) AS max_date
  FROM
    `aparium-dataflow.StarData.MonthlyStar`
),
latest_data AS (
  SELECT *
  FROM `aparium-dataflow.StarData.MonthlyStar` s
  JOIN latest_date d
    ON DATE(s.cy, s.month, 1) = d.max_date
)
SELECT 
  property_code,
  property_name,
  cs_no,
  cy,
  month,
  -- All YTD columns explicitly listed:
  rms_sold_ytd,
  rms_sold_ytd_py,
  rms_sold_pct_chg_ytd,
  rms_sold_pct_chg_ytd_py,
  cs_rms_sold_ytd,
  cs_rms_sold_ytd_py,
  cs_rms_sold_pct_chg_ytd,
  cs_rms_sold_pct_chg_ytd_py,
  available_rms_ytd,
  available_rms_ytd_py,
  available_rms_pct_chg_ytd,
  available_rms_pct_chg_ytd_py,
  cs_available_rms_ytd,
  cs_available_rms_ytd_py,
  cs_available_rms_pct_chg_ytd,
  cs_available_rms_pct_chg_ytd_py,
  occ_ytd,
  occ_ytd_py,
  occ_pct_chg_ytd,
  occ_pct_chg_ytd_py,
  occ_index_ytd,
  occ_index_ytd_py,
  occ_index_pct_chg_ytd,
  occ_index_pct_chg_ytd_py,
  occ_rank_ytd,
  occ_rank_ytd_py,
  occ_rank_pct_chg_ytd,
  occ_rank_pct_chg_ytd_py,
  cs_occ_ytd,
  cs_occ_ytd_py,
  cs_occ_pct_chg_ytd,
  cs_occ_pct_chg_ytd_py,
  adr_ytd,
  adr_ytd_py,
  adr_pct_chg_ytd,
  adr_pct_chg_ytd_py,
  adr_index_ytd,
  adr_index_ytd_py,
  adr_index_pct_chg_ytd,
  adr_index_pct_chg_ytd_py,
  adr_rank_ytd,
  adr_rank_ytd_py,
  adr_rank_pct_chg_ytd,
  adr_rank_pct_chg_ytd_py,
  cs_adr_ytd,
  cs_adr_ytd_py,
  cs_adr_pct_chg_ytd,
  cs_adr_pct_chg_ytd_py,
  rev_ytd,
  rev_ytd_py,
  rev_pct_chg_ytd,
  rev_pct_chg_ytd_py,
  cs_rev_ytd,
  cs_rev_ytd_py,
  cs_rev_pct_chg_ytd,
  cs_rev_pct_chg_ytd_py,
  revpar_ytd,
  revpar_ytd_py,
  revpar_pct_chg_ytd,
  revpar_pct_chg_ytd_py,
  revpar_index_ytd,
  revpar_index_ytd_py,
  revpar_index_pct_chg_ytd,
  revpar_index_pct_chg_ytd_py,
  revpar_rank_ytd,
  revpar_rank_ytd_py,
  revpar_rank_pct_chg_ytd,
  revpar_rank_pct_chg_ytd_py,
  cs_revpar_ytd,
  cs_revpar_ytd_py,
  cs_revpar_pct_chg_ytd,
  cs_revpar_pct_chg_ytd_py
FROM latest_data;